[package]
name = "taiyi-preconfer"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-consensus = { workspace = true }
alloy-contract = { workspace = true }
alloy-eips = { workspace = true }
alloy-network = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-rlp = { workspace = true }
alloy-rpc-client = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-rpc-types-beacon = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-transport = { workspace = true }

axum = { workspace = true }
beacon-api-client = { workspace = true }
cb-common = { git = "https://github.com/lu-bann/commit-boost-client.git", rev = "20a04e9027b473299e736f133cf7392a16ff6bbf" }
cb-pbs = { git = "https://github.com/lu-bann/commit-boost-client.git", rev = "20a04e9027b473299e736f133cf7392a16ff6bbf" }
ethereum-consensus = { workspace = true }
eyre = { workspace = true }
futures = "0.3.30"
mev-share-sse = { git = "https://github.com/paradigmxyz/mev-share-rs" }
parking_lot = { workspace = true }
# cb-crypto = { git = "https://github.com/Commit-Boost/commit-boost-client", rev = "5aca4e2f6e81c6e0132ef3bdfda47922b9bc43a3" }
priority-queue = { workspace = true }
reqwest = "0.12.4"
serde = { workspace = true }
taiyi-primitives = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
alloy-node-bindings = { workspace = true }
mockito = "1.4.0"

[lib]
