[package]
name = "luban-preconfer"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy = { workspace = true }
beacon-api-client = { workspace = true }
cb-common = { git = "https://github.com/Commit-Boost/commit-boost-client", rev = "2fa4b82dd27d39e251b6bd26fd9f07d18586bf4d" }
eyre = { workspace = true }
futures = "0.3.30"
jsonrpsee = { workspace = true }
luban-primitives = { workspace = true }
mev-share-sse = { git = "https://github.com/paradigmxyz/mev-share-rs" }
parking_lot = { workspace = true }
reqwest = "0.12.4"
reth = { git = "https://github.com/paradigmxyz/reth" }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", features = ["serde"] }
reth-node-api = { git = "https://github.com/paradigmxyz/reth" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth" }
reth-provider = { git = "https://github.com/paradigmxyz/reth" }
serde = { workspace = true }
serde_json ={ workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tree_hash = "0.5"
tree_hash_derive = "0.5"
# cb-crypto = { git = "https://github.com/Commit-Boost/commit-boost-client", rev = "5aca4e2f6e81c6e0132ef3bdfda47922b9bc43a3" }

lru = { workspace = true }


[dev-dependencies]
mockito = "1.4.0"

[lib]
