[package]
name = "taiyi-cmd"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-contract = { workspace = true }
alloy-network = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-sol-types = { workspace = true }
blst = { workspace = true }

clap = { workspace = true }
ethereum-consensus = { workspace = true }
eyre = { workspace = true }
hex = "0.4.3"
k256 = { workspace = true }
taiyi-preconfer = { workspace = true }
tiny-bip39 = "1"
# tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
