[package]
name = "taiyi-cli"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-contract = { workspace = true }
alloy-primitives = { workspace = true }
blst = { workspace = true }

clap = { version = "4.5.4", features = ["derive"] }
ethereum-consensus = { workspace = true }
eyre = { workspace = true }
hex = "0.4.3"
taiyi-preconfer = { workspace = true }
tiny-bip39 = "1"
tokio = { workspace = true }
