[package]
name = "taiyi-fraud-proof-cli"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
clap = { workspace = true }
eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sp1-sdk = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
sp1-build = { workspace = true }
