[package]
name = "taiyi-primitives"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-consensus = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
alloy-rpc-types-beacon = { workspace = true }
alloy-sol-types = { workspace = true }
beacon-api-client = { workspace = true }
ethereum-consensus = { workspace = true }
serde = { workspace = true }
ssz_rs = { workspace = true }

[lib]
