[package]
name = "luban-primitives"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy = { workspace = true }
alloy-rlp = { version = "0.3.4", features = ["derive"] }
ethereum_ssz = "0.5.4"
ethereum_ssz_derive = "0.5.4"
serde = { workspace = true }
serde_json ={ workspace = true }

[lib]
