[package]
name = "taiyi-primitives"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rlp = { workspace = true }
alloy-rpc-types-beacon = { workspace = true }
alloy-sol-types = { workspace = true }
beacon-api-client = { workspace = true }
derive_more = { workspace = true }
ethereum-consensus = { workspace = true }
hex = "0.4.3"
reth-primitives = { workspace = true }
serde = { workspace = true }
sha2 = "0.10.8"
ssz_rs = { workspace = true }

[lib]
