[package]
name = "taiyi-underwriter"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-consensus = { workspace = true, features = ["kzg"] }
alloy-contract = { workspace = true }
alloy-eips = { workspace = true }
alloy-network = { workspace = true }
alloy-primitives = { workspace = true }
alloy-provider = { workspace = true, features = ["debug-api"] }
alloy-rpc-client = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-rpc-types-beacon = { workspace = true }
alloy-rpc-types-trace = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-transport = { workspace = true }

axum = { workspace = true }
blst = { workspace = true }
ethereum-consensus = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
k256 = { workspace = true }
lazy_static = { workspace = true }
mev-share-sse = { git = "https://github.com/paradigmxyz/mev-share-rs", rev = "a75c5959e98a79031a89f8893c97528e8f726826" }
parking_lot = { workspace = true }
prometheus = { workspace = true }
reqwest = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3.12.0"
ssz_rs = { workspace = true }
taiyi-beacon-client = { workspace = true }
taiyi-primitives = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-stream = "0.1.17"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tree_hash = "0.6.0"
tree_hash_derive = "0.6.0"
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
alloy-node-bindings = { workspace = true }
mockito = "1.4.0"
reqwest-eventsource = "0.6"
