# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "prague"           # to add BLS precompile
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = false
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  fs_permissions = [{ access = "read-write", path = "./" }]
  solc = "0.8.27"
  src = "src"
  test = "test"
  via_ir = false

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin-contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/",
  "@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
  "@eigenlayer-middleware/=lib/eigenlayer-middleware/",
  "@eigenlayer-contracts/=lib/eigenlayer-contracts/",
  "@symbiotic/=lib/middleware-sdk/lib/core/src",
  "@symbiotic-test/=lib/middleware-sdk/lib/core/test/",
  "@sp1-contracts/=lib/sp1-contracts/contracts/src/",
  "@urc/=lib/urc/src",
  "@solady/=lib/solady/src",

  "@symbiotic-middleware-sdk/=lib/middleware-sdk/src/",

  "lib/eigenlayer-contracts/:@openzeppelin/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-v4.9.0/",
  "lib/eigenlayer-contracts/:@openzeppelin-v4.9.0/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-v4.9.0/contracts/",
  "lib/eigenlayer-contracts/:@openzeppelin-upgrades-v4.9.0/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-upgradeable-v4.9.0/contracts/",
  "lib/eigenlayer-contracts/:@openzeppelin-upgrades/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-upgradeable-v4.9.0/",
  "lib/eigenlayer-contracts/:ds-test/=lib/eigenlayer-contracts/lib/ds-test/src/",
  "lib/eigenlayer-contracts/lib/openzeppelin-contracts/:@openzeppelin/contracts/=lib/eigenlayer-contracts/lib/openzeppelin-contracts/contracts/",
  
  "lib/core/:@openzeppelin/contracts/=lib/core/lib/openzeppelin-contracts/contracts/",

  "lib/middleware-sdk/:@openzeppelin/contracts/=lib/middleware-sdk/lib/openzeppelin-contracts/contracts/",
  "lib/middleware-sdk/:@openzeppelin/contracts-upgradeable/=lib/middleware-sdk/lib/openzeppelin-contracts-upgradeable/contracts/",
  "lib/middleware-sdk/:@symbiotic/=lib/middleware-sdk/lib/core/src/",
  "lib/middleware-sdk/:@symbiotic-test/=lib/middleware-sdk/lib/core/test/",
  "lib/middleware-sdk/:@crypto-lib/=lib/middleware-sdk/lib/crypto-lib/src/",
  "lib/middleware-sdk/:forge-std/=lib/middleware-sdk/lib/forge-std/src/",

  "lib/openzeppelin-contracts-upgradeable/:@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/"
]

[profile.ci]
  auto_detect_solc = false
  block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "paris"           # See https://www.evmdiff.com/features?name=PUSH0&kind=opcode
  fuzz = { runs = 1_000 }
  gas_reports = ["*"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  fs_permissions = [{ access = "read-write", path = "./" }]
  solc = "0.8.27"
  src = "src"
  test = "test"
  via_ir = true

# [etherscan]
#   arbitrum = { key = "${API_KEY_ARBISCAN}" }
#   avalanche = { key = "${API_KEY_SNOWTRACE}" }
#   bnb_smart_chain = { key = "${API_KEY_BSCSCAN}" }
#   gnosis_chain = { key = "${API_KEY_GNOSISSCAN}" }
#   goerli = { key = "${API_KEY_ETHERSCAN}" }
#   mainnet = { key = "${API_KEY_ETHERSCAN}" }
#   optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
#   polygon = { key = "${API_KEY_POLYGONSCAN}" }
#   sepolia = { key = "${API_KEY_ETHERSCAN}" }

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 90
  sort_imports = true
  contract_new_line = true
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = false

[rpc_endpoints]
  arbitrum = "https://arbitrum-mainnet.infura.io/v3/${API_KEY_INFURA}"
  avalanche = "https://avalanche-mainnet.infura.io/v3/${API_KEY_INFURA}"
  bnb_smart_chain = "https://bsc-dataseed.binance.org"
  gnosis_chain = "https://rpc.gnosischain.com"
  goerli = "https://goerli.infura.io/v3/${API_KEY_INFURA}"
  localhost = "http://localhost:8545"
  mainnet = "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}"
  optimism = "https://optimism-mainnet.infura.io/v3/${API_KEY_INFURA}"
  polygon = "https://polygon-mainnet.infura.io/v3/${API_KEY_INFURA}"
  sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"